[package]
name = "digital-garden"
description = "A tool for authoring and syncing digital gardens"
version = "0.1.0"
authors = ["Christopher Biscardi <chris@christopherbiscardi.com>"]
edition = "2018"
license = "MIT"
readme = "./README.md"
keywords = ["garden", "digital"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "garden"
path = "src/main.rs"

[dependencies]
directories = "3.0.1"
color-eyre = "0.5.6"
tracing = "0.1.21"
structopt = "0.3.19"
edit = "0.1.2"
rprompt = "1.0.5"
slug = "0.1.4"
owo-colors = "1.1.3"
serde = "1.0.116"
[dependencies.confy]
git = "https://github.com/rust-cli/confy"
commit = "baf2b401c9b4e783599ac8c74a6a9829a27f0deb"
features = ["yaml_conf"]
default-features = false

[dev-dependencies]
assert_fs = "1.0.0"
escargot = "0.5.0"
assert_cmd = "1.0.1"
